### PR TITLE
discuss extensibility

### PR DESCRIPTION
**Pull request by kazuho**
I think calling out extension points, at the same time clarifying why it can be left as future work is beneficial for pushing the specification forward.

@LPardue  WDYT?

### CODE REVIEW

**Review by LPardue — APPROVED** [review]
LGTM.

One tangential clarification question. I read the ABNF to allow priority-directive to be either 

```
directive=value
```

or

```
directive
```

Do you think an extension would use the latter syntax? I think your examples would probably use a value.

**Comment by LPardue** [comment]
FWIW another kind of extensibility is a priority-related header. For example, on the Cloudflare blog we explain a `cf-priority` header and a `cf-priority-change header` [1]. 

This allows something like 

```
cf-priority = value #initial value
cf-priority-change = 512:new value # priority value after 512 bytes of response was streamed
```

I'm not suggesting adding something like this now, but it is an example of the flexibility/extensibility of using headers. Furhtermore, the advantage on using headers over frames is that the Web platform has many APIs for Headers. In contrast, HTTP/2 frames have difficulty here.


[1] - https://blog.cloudflare.com/parallel-streaming-of-progressive-images/

**Comment by kazuho** [comment]
Thank you for checking. Merged, as I believe that your comments are better to be solved separately (if necessary).

Regarding the points you have raised, I will respond here in a separate comment.

**Comment by kazuho** [comment]
> One tangential clarification question. I read the ABNF to allow priority-directive to be either
> ```
> directive=value
> ```
> 
> or
> ```
> directive
> ```
> 
> Do you think an extension would use the latter syntax? I think your examples would probably use a value.

I think we should require the values of the parameters to be specified explicitly. IMO that's simpler, and there's no overhead in terms of bytes on the wire once HPACK/QPACK is applied. I think #9 has implies that by stating that the values are sh-token (or sh-boolean), but we can be more explicit.

I will prepare a PR that clarifies that. Please let me know if you prefer allowing omission of values.

**Comment by kazuho** [comment]
Re https://github.com/kazuho/draft-kazuho-httpbis-priority/pull/7#issuecomment-507221127, I totally agree that the `cf-priority-change` header field is a brilliant example of extensibility that a header-based design can provide.

Do you want to mention that in the I-D? The problem in terms of writing it in I-D is that the `cf-priority-change` header is essentially a reprioritization instruction. Therefore, trying to write it down could mean that we'd have certain amount of considerations covering reprioritization (relates to #1).

Regardless of what we decide on I-D, I think we should use `cf-priority-change` as an example on the mailing list / in the presentations.

**Comment by LPardue** [comment]
> I think we should require the values of the parameters to be specified explicitly. IMO that's simpler, and there's no overhead in terms of bytes on the wire once HPACK/QPACK is applied. I think #9 has implies that by stating that the values are sh-token (or sh-boolean), but we can be more explicit.

As an implementer I prefer explicit values.

> Do you want to mention that in the I-D? The problem in terms of writing it in I-D is that the cf-priority-change header is essentially a reprioritization instruction. Therefore, trying to write it down could mean that we'd have certain amount of considerations covering reprioritization (relates to #1).

> Regardless of what we decide on I-D, I think we should use cf-priority-change as an example on the mailing list / in the presentations.

Sorry to have raised that point on this PR. I agree it is related to reprioritization and that we should tackle it as part of #1. I'll add a comment there so we don't lose track. Adding it to the I-D now is a bit distracting regardless of how useful it is to the broader discussion.

**Pull request merged**
